name: centralizador
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  flutter_local_notifications: ^14.0.0
  provider: ^6.1.2
  cached_network_image: ^3.2.1
  carousel_slider: ^4.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
