name: centralizador
description: "Uma aplicação usada para centralizar os links da instituição BBS Ltda"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  provider: ^6.1.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  flutter_local_notifications: ^17.2.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
    - assets/images/Marca_Bright_Bee.png
    - assets/images/fundo_papel_amassado.png
    - assets/images/fundo_correto.png
